# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TRAIN_SUBJECTS": "00_utils.ipynb",
         "TEST_SUBJECTS": "00_utils.ipynb",
         "H36M_NAMES": "00_utils.ipynb",
         "N_CAMERAS": "00_utils.ipynb",
         "N_JOINTS": "00_utils.ipynb",
         "PLOT_RADIUS": "00_utils.ipynb",
         "Path.ls": "00_utils.ipynb",
         "data_path": "00_utils.ipynb",
         "get_actions": "00_utils.ipynb",
         "normalize_data": "00_utils.ipynb",
         "unnormalize_data": "00_utils.ipynb",
         "normalize_kp": "00_utils.ipynb",
         "get_kp_from_json": "00_utils.ipynb",
         "coco_to_skel": "00_utils.ipynb",
         "get_cam_rt": "00_utils.ipynb",
         "camera_to_world_frame": "00_utils.ipynb",
         "cam_to_world_centered": "00_utils.ipynb",
         "show_2d_pose": "00_utils.ipynb",
         "show_3d_pose": "00_utils.ipynb",
         "Human36Dataset": "02_dataset.ipynb",
         "init_kaiming": "03_model.ipynb",
         "ResLinear": "03_model.ipynb",
         "Model": "03_model.ipynb"}

modules = ["utils.py",
           "dataset.py",
           "model.py"]

doc_url = "https://denilson020898.github.io/baseline_3d_pose/"

git_url = "https://github.com/denilson020898/baseline_3d_pose/tree/master/"

def custom_doc_links(name): return None
