# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TRAIN_SUBJECTS": "00_data.ipynb",
         "TEST_SUBJECTS": "00_data.ipynb",
         "H36M_NAMES": "00_data.ipynb",
         "get_actions": "00_data.ipynb",
         "normalize": "00_data.ipynb",
         "unnormalize": "00_data.ipynb"}

modules = ["data.py"]

doc_url = "https://denilson020898.github.io/baseline_3d_pose/"

git_url = "https://github.com/denilson020898/baseline_3d_pose/tree/master/"

def custom_doc_links(name): return None
